### PR TITLE
Create single executable

### PR DESCRIPTION
**Pull request by hous3m4ster**
Commit below implements a singlefile option for pyinstaller, creating a single executable.

Also added a gitignore

### CODE REVIEW

**Comment by m-jeu** [comment]
Tried this a while ago but firewall blocked application excecution at every possible turn, not allowing user to circumvent it. Having a folder instead of a single excecutable is worth it if it improves easy of use for people without affinity for computers in my opinion

**Comment by hous3m4ster** [comment]
Hm, weird, not experiencing this myself 🤔

**Comment by m-jeu** [comment]
I believe it's a known problem

**Comment by hous3m4ster** [comment]
If you're talking about Smart Screen, I can understand your point, but the current implementation also gets blocked by smart screen. This is because the exe is not signed.

**Comment by hous3m4ster** [comment]
Closed as won't implement

**Pull request closed without merging**
